window.COURSE_WEEKS = window.COURSE_WEEKS || [];
window.COURSE_WEEKS.push({
  week: 1,
  title: "Foundations & Your Idea",
  goal: "Understand how apps and app businesses work, then pick one validated idea.",
  days: [
    {
      day: 1,
      title: "How Apps Actually Work",
      emoji: "🧠",
      intro: "You don't need to write code to build apps anymore — but you DO need a mental model of what an app is, so you can direct AI like a project manager instead of guessing.",
      cards: [
        { t: "An app is just three layers", d: "Every app — Instagram, Notion, your future product — has the same three layers:\n1) Frontend: what the user sees and taps (screens, buttons, text).\n2) Backend: the logic that runs on a server (checking passwords, processing payments).\n3) Database: where information is stored (users, messages, subscriptions).\nWhen you ask AI to build something, you're asking it to write these three layers." },
        { t: "The frontend is HTML, CSS and JavaScript", d: "Web frontends are built from three file types:\n• HTML — the content and structure (\"there is a button here\").\n• CSS — the styling (\"the button is green and rounded\").\n• JavaScript — the behavior (\"when tapped, save the note\").\nYou won't write these by hand. But knowing the names lets you say things like \"change the CSS so the button is bigger\" — and AI will know exactly what you mean." },
        { t: "APIs are how software talks to software", d: "An API (Application Programming Interface) is a doorway that lets one program use another. Your app can use Stripe's API to charge cards, OpenAI or Anthropic's API to add AI features, and a weather API to show forecasts.\nThis is the indie hacker superpower: you don't build payments or AI from scratch — you plug in APIs that already exist and pay per use." },
        { t: "A web app beats a mobile app to start", d: "A web app runs in the browser and works on every phone and laptop instantly. No App Store review, no 30% Apple fee on your subscriptions, updates go live in seconds.\nA PWA (progressive web app) can even be installed to the home screen like a native app. Almost every successful indie hacker starts on the web and only builds native mobile apps later, if ever." },
        { t: "AI writes the code, you make the decisions", d: "Tools like Claude Code, Cursor, Bolt and Lovable can generate an entire working app from a plain-English description. What they can't do is decide WHAT to build, WHO it's for, and WHAT to charge.\nThat's your job for the next 30 days: learn just enough about each layer to give great instructions, judge the output, and ship." }
      ],
      action: "Open one app you use daily and identify its three layers out loud: what's the frontend (what you see), what must the backend be doing, and what is probably stored in the database?",
      quiz: [
        { q: "What are the three layers of every app?", a: ["Frontend, backend, database", "HTML, Python, WiFi", "App Store, website, server", "Design, marketing, sales"], c: 0, e: "Frontend (what users see), backend (logic on a server), and database (stored information). Every app you'll ever build with AI is some combination of these three." },
        { q: "In a web app, what does CSS control?", a: ["How things look — colors, sizes, layout", "Where data is stored", "Payment processing", "The app's logic and behavior"], c: 0, e: "CSS is the styling layer. HTML is structure, CSS is looks, JavaScript is behavior. Knowing these three words makes your AI prompts dramatically more precise." },
        { q: "What is an API best described as?", a: ["A doorway that lets one program use another program's abilities", "A type of database", "A programming language", "An app icon format"], c: 0, e: "APIs let your app plug into existing services — Stripe for payments, Anthropic for AI, and thousands more — instead of building everything yourself." },
        { q: "Why do most indie hackers launch as a web app instead of an iOS app?", a: ["No app store review, no 30% fee, instant updates, works everywhere", "Web apps are always faster than native apps", "Apple doesn't allow indie developers", "Web apps don't need a backend"], c: 0, e: "The web means you ship today, keep ~97% of revenue (minus payment fees), and update anytime. Native apps can come later once you have paying users." },
        { q: "What's YOUR most important job when building with AI?", a: ["Deciding what to build, for whom, and what to charge", "Memorizing JavaScript syntax", "Writing code faster than the AI", "Designing app icons"], c: 0, e: "AI handles the code. Your judgment about the problem, the customer, and the business is what actually creates revenue — and no tool can replace it." }
      ]
    },
    {
      day: 2,
      title: "Your AI Toolkit",
      emoji: "🧰",
      intro: "There are dozens of AI coding tools. You only need to understand four categories — and you'll probably use just two of them.",
      cards: [
        { t: "Category 1: Chat assistants", d: "ChatGPT and Claude (the chat apps) are your thinking partners. Use them to brainstorm ideas, critique your pricing, explain confusing errors in plain English, and draft marketing copy.\nThey can write code snippets too, but copy-pasting code from a chat window gets painful fast — that's what the next categories fix." },
        { t: "Category 2: Prompt-to-app builders", d: "Bolt, Lovable, and v0 let you type \"build me a habit tracker with a paywall\" and watch a working app appear in the browser. Zero setup — perfect for prototypes and testing ideas fast.\nThe tradeoff: you're renting their platform, and complex apps eventually hit walls. Great for week one prototypes, risky as your only skill." },
        { t: "Category 3: AI coding agents", d: "Claude Code and Cursor work directly with real code files on a real project. You describe what you want; the agent writes, edits, runs, and fixes the code across your whole project.\nThis is the pro indie stack: you own the code, nothing is locked to a platform, and there's no ceiling on what you can build. This course prepares you for exactly this." },
        { t: "Category 4: The services you plug in", d: "You'll rely on a few hosted services so you never manage servers:\n• GitHub — stores your code and its full history.\n• Vercel or Netlify — puts your app on the internet in one click.\n• Supabase or Firebase — database + user accounts, ready-made.\n• Stripe (or Lemon Squeezy) — takes payments.\nAll have generous free tiers. You can run a real product for $0–20/month." },
        { t: "The workflow you're learning", d: "Here's the loop you'll repeat for every app you ever build:\n1) Describe a small piece of the app to an AI agent.\n2) Look at what it built. Test it like a customer would.\n3) Say what's wrong or what's next. Repeat.\n4) Push to GitHub, deploy, share the link.\nPeople call it \"vibe coding\". It's really just fast, cheap iteration — the thing startups always wanted." }
      ],
      action: "Create a free GitHub account at github.com (if you don't have one). It takes 2 minutes and you'll need it from Week 2 onward.",
      quiz: [
        { q: "What are chat assistants like Claude and ChatGPT best used for in your workflow?", a: ["Brainstorming, explaining errors, critiquing plans, drafting copy", "Hosting your app", "Storing your database", "Processing payments"], c: 0, e: "Chat assistants are your thinking partners. For writing whole apps, dedicated coding agents like Claude Code or builders like Bolt are the better fit." },
        { q: "What's the main risk of building only with prompt-to-app platforms like Bolt or Lovable?", a: ["You're dependent on their platform and can hit complexity walls", "They can't make anything visual", "They cost thousands per month", "They require a computer science degree"], c: 0, e: "They're fantastic for fast prototypes, but for a long-term product you want code you own — which agents like Claude Code and Cursor give you." },
        { q: "What does Vercel or Netlify do for you?", a: ["Puts your app live on the internet with one click", "Writes your marketing emails", "Designs your logo", "Replaces your database"], c: 0, e: "These are hosting platforms. Connect your GitHub repository and every change you push goes live automatically — no servers to manage." },
        { q: "Which pair gives you a ready-made database AND user accounts?", a: ["Supabase or Firebase", "Stripe or PayPal", "Bolt or Lovable", "GitHub or GitLab"], c: 0, e: "Supabase and Firebase are 'backend as a service' — database, login, and file storage without building any of it. You'll meet them properly in Week 3." },
        { q: "What is the core loop of building with AI (\"vibe coding\")?", a: ["Describe a small piece → test it → give feedback → repeat", "Write a 50-page spec, then generate the app once", "Copy code from tutorials until it works", "Hire a developer to review every line"], c: 0, e: "Small steps with fast feedback beat giant one-shot prompts. You'll get better results asking for one feature at a time and testing as you go." }
      ]
    },
    {
      day: 3,
      title: "MRR: The Business Model",
      emoji: "💰",
      intro: "Before building anything, understand the money. MRR — monthly recurring revenue — is why software is the best small business in the world.",
      cards: [
        { t: "Why recurring beats one-time", d: "Sell a $50 one-time product and next month you start at $0 again. Sell a $10/month subscription and next month starts at $10, then $20, then $30 as customers stack.\nMRR compounds: 30 new subscribers a month at $10 gets you to ~$3,000/month within a year even with some cancellations. That's why this course aims you at subscription products." },
        { t: "The four numbers that matter", d: "• MRR — total subscription revenue per month.\n• Churn — % of customers who cancel each month. Under 5% is decent, under 3% is good.\n• LTV (lifetime value) — average total revenue per customer. Roughly: price ÷ churn rate. $10/month with 5% churn ≈ $200 LTV.\n• CAC (customer acquisition cost) — what you spend to get one customer. Indie hackers aim for ~$0 via content, SEO and communities." },
        { t: "The realistic math to $5k/month", d: "$5,000 MRR is roughly:\n• 500 customers at $10/month, or\n• 167 customers at $30/month, or\n• 56 customers at $90/month.\nNotice: fewer customers at higher prices is usually easier. Selling to businesses (B2B) supports higher prices than selling to consumers — a tool that saves a business an hour a week is easily worth $30/month." },
        { t: "Niche down until it feels too small", d: "\"Todo app\" competes with Apple and Google. \"Job-costing tool for solo landscapers\" competes with nobody.\nA niche of 5,000 potential customers where 1% convert at $29/month is $1,450 MRR from ONE small app. Niches feel scary because they're small — that's exactly what makes them winnable for a solo founder." },
        { t: "Think portfolio, not lottery ticket", d: "Most successful indie hackers didn't hit a home run on app #1. They shipped small bets — app #1 made $0, #2 made $200/month, #4 made $2k/month.\nEach launch costs you weeks now, not years, because AI does the building. Your goal this month is to complete the full loop once: idea → build → launch → first dollar. The loop is the skill; the apps are just at-bats." }
      ],
      action: "Write down your personal MRR goal (e.g. $2,000/month) and calculate two paths to it: how many customers at $10/month, and how many at $29/month?",
      quiz: [
        { q: "Why is MRR better than one-time sales for a solo founder?", a: ["Revenue compounds month over month instead of resetting to zero", "Subscriptions are easier to build technically", "One-time products are illegal in app stores", "Customers prefer paying forever"], c: 0, e: "Each month's new customers stack on top of existing ones. One-time sales mean starting from zero every month — a treadmill that never slows down." },
        { q: "What is churn?", a: ["The percentage of customers who cancel each month", "Your monthly hosting bill", "The number of new signups", "Profit after taxes"], c: 0, e: "Churn is the leak in your bucket. A $10/month product with 5% monthly churn keeps the average customer ~20 months (~$200 lifetime value)." },
        { q: "Roughly how many $30/month customers do you need for $5,000 MRR?", a: ["About 167", "About 1,000", "About 20", "About 5,000"], c: 0, e: "5000 ÷ 30 ≈ 167 customers. Compare that to 500 customers at $10 — higher prices mean fewer customers needed, which is why B2B niches are indie-friendly." },
        { q: "Why is \"invoice tool for solo landscapers\" a better indie idea than \"todo app\"?", a: ["A tight niche has reachable customers and weak competition", "Landscapers pay more than everyone else", "Todo apps are impossible to build", "Niche apps don't need marketing"], c: 0, e: "You can't out-build Apple at todo apps. But nobody at Apple is waking up thinking about solo landscapers' invoicing — that's your opening." },
        { q: "What's the smartest mindset for your first app?", a: ["It's one bet in a portfolio — the goal is completing the loop from idea to first dollar", "It must be a home run or you've failed", "Spend a year perfecting it before showing anyone", "Copy the #1 app in the App Store exactly"], c: 0, e: "AI makes each attempt cheap. Ship, learn, ship again. Most indie fortunes are a portfolio of small bets, not one lottery ticket." }
      ]
    },
    {
      day: 4,
      title: "Finding Ideas That Pay",
      emoji: "💡",
      intro: "Good news: you don't need a brilliant original idea. You need a boring, painful problem that a specific group of people will pay to make go away.",
      cards: [
        { t: "Problems first, ideas second", d: "Apps that make money are painkillers, not vitamins. People pay to remove pain: wasted hours, lost money, anxiety, embarrassment.\nThe question is never \"what app should I build?\" It's \"who has a recurring, expensive, annoying problem — and what would they pay to never feel it again?\"" },
        { t: "Mine your own life and work", d: "The best idea sources are unfair advantages you already have:\n• Your day job — every spreadsheet you maintain by hand is an app idea.\n• Your hobbies — you know what fellow hobbyists complain about.\n• Your communities — what does everyone in your group chat moan about?\nYou understand these customers because you ARE one. That beats any market research." },
        { t: "Spy on demand that already exists", d: "Proof people pay is better than a clever guess:\n• Read 1-star reviews of popular paid apps — each complaint is a gap.\n• Search Reddit for \"is there a tool that…\" and \"I'd pay for…\" in niche subreddits.\n• Browse what's selling on marketplaces and directories in your niche.\nCompetition is GOOD. It proves money exists. You just need an angle: cheaper, simpler, or more specific to one audience." },
        { t: "The B2B cheat code", d: "Businesses buy differently than consumers: they pay 5–10× more, cancel less, and buy on ROI (\"this saves me 2 hours a week\") rather than mood.\nSmall service businesses are the sweet spot — cleaners, tutors, coaches, agencies, tradespeople. They're drowning in admin work, underserved by big software, and reachable in Facebook groups and subreddits." },
        { t: "Score your ideas with PAINS", d: "Rate each idea 1–5 on:\n• Painful — does it hurt weekly or daily?\n• Audience — can you name and reach the buyers?\n• Income — do they have money and a habit of spending it?\n• Narrow — is it specific enough to win?\n• Simple — could v1 be ONE core feature?\nAnything scoring 20+ is worth validating tomorrow." }
      ],
      action: "Write down 10 problem-based ideas (not features — problems). Use your job, hobbies, and communities. Then score each with PAINS and circle your top 3.",
      quiz: [
        { q: "What kind of product is most likely to make money?", a: ["A painkiller that removes a recurring, expensive annoyance", "A vitamin that's nice to have", "The most original idea nobody has tried", "The prettiest app in its category"], c: 0, e: "People reliably pay to make pain stop. 'Nice to have' products get praise and no credit card numbers." },
        { q: "Why are your own job, hobbies, and communities the best idea sources?", a: ["You deeply understand the customer because you are one", "They're the only legal sources of ideas", "Ideas from your life can't have competitors", "You can skip building a product"], c: 0, e: "Founder-market fit is an unfair advantage: you know the vocabulary, the pain, and where these people hang out online." },
        { q: "You find 3 competitors already charging for your idea. What does this mean?", a: ["Money exists here — find your angle (cheaper, simpler, or more niche)", "The idea is dead, move on", "You must build every feature they have", "You should sue them"], c: 0, e: "Competition validates demand. A crowded market with mediocre 1-star-review-riddled products is a classic indie opportunity." },
        { q: "Why is B2B (selling to businesses) an indie cheat code?", a: ["Businesses pay more, churn less, and buy on ROI", "Businesses never cancel subscriptions", "B2B apps don't need marketing", "Consumers are illegal to sell to"], c: 0, e: "A tool that saves a business time or wins them clients justifies $30–100/month easily. The same tool for consumers might struggle at $5." },
        { q: "In the PAINS score, what does 'Simple' check for?", a: ["Version 1 could be a single core feature", "The app uses no database", "The idea has no competitors", "The name is easy to spell"], c: 0, e: "Scope kills first apps. If v1 can't be one core feature built in a couple of weeks, save the idea for later and pick a simpler bet." }
      ]
    },
    {
      day: 5,
      title: "Validate Before You Build",
      emoji: "🔍",
      intro: "The #1 indie mistake: spending 3 months building something nobody wants. Today you learn to test demand in days, before writing a single prompt.",
      cards: [
        { t: "Validation = evidence people will PAY", d: "Compliments are not validation. \"Cool idea!\" costs the speaker nothing.\nEvidence looks like: people already paying for worse alternatives, people signing up with their email after reading your pitch, people pre-ordering, or people describing the problem unprompted in communities. Collect evidence, not applause." },
        { t: "Talk to 5 real humans", d: "Find 5 people in your target niche (Reddit, Facebook groups, your own network). Don't pitch — ask about their life:\n• \"How do you handle X today?\"\n• \"What's the most annoying part?\"\n• \"Have you tried other tools? Why did you quit them?\"\n• \"What would solving this be worth per month?\"\nIf nobody describes the problem as painful without your prompting, that's your answer." },
        { t: "The landing page smoke test", d: "Before building the app, build a one-page site (AI makes this a 30-minute job — you'll do it Day 11):\n• Headline stating the outcome you deliver.\n• 3 bullet benefits. A mockup image.\n• A price and a \"Get early access\" email box.\nShare it in 2–3 niche communities. 20–30%+ of visitors leaving an email = strong signal. Crickets = you just saved yourself a month." },
        { t: "Check search demand", d: "People type their pain into Google. Free ways to check:\n• Google's autocomplete — start typing the problem and read the suggestions.\n• \"People also ask\" boxes on results pages.\n• Reddit/forum threads ranking for the problem (that's demand with no good answer).\nIf literally nobody searches for the problem or its solutions, be suspicious: you may have invented a problem." },
        { t: "Kill ideas cheerfully", d: "Expect 2 of your top 3 ideas to fail validation. That's the system working — each dead idea cost you days, not months.\nDecision rule after ~1 week of validating: strong pain in interviews + emails collected + evidence of spending = BUILD. Anything less = pick the next idea from your list. You're not married to ideas; you're dating them." }
      ],
      action: "Post one genuine question about your top idea's problem in a niche community (Reddit, Facebook group, Discord). Ask how people handle it today — don't pitch anything.",
      quiz: [
        { q: "What counts as real validation?", a: ["Evidence of willingness to pay — emails, pre-orders, money spent on alternatives", "Friends saying the idea is cool", "A high score on your own PAINS sheet", "AI saying the idea is good"], c: 0, e: "Talk is free, so it proves nothing. Emails, pre-orders, and existing spending are costly signals — those are the ones to trust." },
        { q: "In customer interviews, why ask \"How do you handle this today?\" instead of pitching your idea?", a: ["Current behavior reveals true pain; reactions to pitches are polite lies", "It's faster than pitching", "Pitching is illegal before incorporation", "It tricks them into buying"], c: 0, e: "People are nice — they'll praise your pitch to your face. But how they actually spend time and money today can't lie." },
        { q: "What is a landing page smoke test?", a: ["A one-page pitch with an email signup, shared before the product exists", "Testing if your server catches fire", "A/B testing two logos", "A page that only loads on phones"], c: 0, e: "It tests the promise before you build the product. Strong email conversion = build. Silence = next idea, one month of your life saved." },
        { q: "Your landing page gets 200 visitors and 2 emails (1%). What's the honest read?", a: ["Weak demand or weak pitch — rework the offer or move to the next idea", "Great result, start building the full app", "The visitors were all robots", "You need a prettier logo"], c: 0, e: "Interested niche traffic should convert at 20%+ for an early-access list. 1% says the promise isn't landing. Cheap lesson — that's the point of testing." },
        { q: "Two of your three ideas fail validation. What does this mean?", a: ["The system is working — each failure cost days instead of months", "You're bad at ideas and should stop", "Validation doesn't work", "You should build all three anyway"], c: 0, e: "Killing bad ideas quickly is the skill. Every dead idea redirects your limited time toward the one worth building." }
      ]
    },
    {
      day: 6,
      title: "Choose Your Stack",
      emoji: "🏗️",
      intro: "A 'stack' is just the set of tools your app is built with. Here's the boring, reliable, nearly-free stack that fits AI-assisted beginners perfectly.",
      cards: [
        { t: "The indie starter stack", d: "• Code: written by Claude Code or Cursor, stored on GitHub.\n• App: a web app (Next.js or plain HTML/JS — your AI will recommend per project).\n• Hosting: Vercel or Netlify (free tier).\n• Database + login: Supabase (free tier).\n• Payments: Stripe, or Lemon Squeezy if you want them to handle sales tax.\nThis exact stack runs thousands of profitable indie apps." },
        { t: "Why this stack works for non-coders", d: "Three reasons:\n1) It's the most common stack on the internet — AI tools have seen millions of examples, so they generate excellent code for it.\n2) Every service is managed — no servers to secure or update at 3am.\n3) Free tiers cover you until you have real revenue. You pay when you're earning." },
        { t: "Let AI make the technical calls", d: "You choose the product; the AI chooses implementation details. A great kickoff prompt pattern:\n\"I'm a non-technical founder building [idea] for [audience]. Recommend the simplest stack using Supabase, Vercel and Stripe, then set up the project.\"\nWhen AI offers options, ask: \"Which is simplest to maintain for a beginner? Decide for me and explain in one paragraph.\"" },
        { t: "What your money buys (roughly)", d: "Monthly costs to expect:\n• Domain name: ~$1/month (about $12/year).\n• Hosting, database, code storage: $0 on free tiers.\n• AI coding tool: ~$20/month — your only real cost, and it replaces a $10k/month developer.\nTotal: about $21/month to run a real software business. Your first two customers cover it." },
        { t: "Avoid these beginner traps", d: "• Don't build native iOS/Android first — slower, gated, 30% fees.\n• Don't rent no-code platforms with per-user pricing that eats your margin at scale (fine for prototypes only).\n• Don't run your own server — managed services exist so you can sleep.\n• Don't chase exotic new frameworks — boring and common means AI writes it better and Google has every answer." }
      ],
      action: "Buy a domain for your top idea (Namecheap/Cloudflare/Porkbun, ~$12). Weird-but-memorable beats perfect-but-taken. This small purchase makes the project real.",
      quiz: [
        { q: "What does a 'stack' mean?", a: ["The set of tools and services an app is built with", "A pile of unread documentation", "A type of database table", "The app's price tiers"], c: 0, e: "Frontend framework, hosting, database, payments — together, that's your stack. Yours: AI-written code, GitHub, Vercel, Supabase, Stripe." },
        { q: "Why does using the most COMMON stack help when AI writes your code?", a: ["AI has seen millions of examples, so it generates better code and fixes for it", "Common stacks are legally required", "Rare stacks cost more to host", "Common stacks never have bugs"], c: 0, e: "AI is strongest on patterns it has seen most. Boring, popular technology = better generations, better debugging, better answers online." },
        { q: "Roughly what does it cost per month to run a first indie app on this stack?", a: ["About $20 — mostly the AI coding tool", "About $500 for servers", "About $2,000 for a developer", "Nothing at all, forever"], c: 0, e: "Free tiers cover hosting, database, and code storage. The ~$20 AI subscription is your one real cost — it's doing the work of a developer." },
        { q: "When your AI offers three technical options you don't understand, what's the move?", a: ["Ask it to pick the simplest for a beginner to maintain, and explain why briefly", "Always pick the first option", "Stop the project until you learn to code", "Pick the one with the coolest name"], c: 0, e: "You're the CEO, not the engineer. Delegate the decision but require a plain-English rationale — you'll learn a little more each time." },
        { q: "Which of these is a beginner trap?", a: ["Building a native iPhone app as your very first product", "Using a boring, popular stack", "Using free tiers until you have revenue", "Letting managed services run your database"], c: 0, e: "Native mobile means App Store review, 30% fees, and slower iteration. Start on the web; go native later if customers demand it." }
      ]
    },
    {
      day: 7,
      title: "Checkpoint: Commit to One Idea",
      emoji: "🎯",
      intro: "Week 1 ends with a decision. Ideas are cheap and infinite — momentum comes from picking ONE and refusing to switch for 30 days.",
      cards: [
        { t: "Make the call", d: "Look at your validation evidence from Day 5 and pick your one idea. Write this sentence and put it somewhere visible:\n\"I'm building [app] that helps [specific niche] [get outcome], for [price]/month.\"\nExample: \"I'm building QuoteFast, which helps solo landscapers send professional quotes in 2 minutes, for $19/month.\"\nIf you genuinely can't choose, pick the one with the most reachable audience. Deciding beats optimizing." },
        { t: "Scope version 1 ruthlessly", d: "Write two lists:\n• v1 (build now): the ONE core action that delivers the outcome, plus login and payments. That's it.\n• Later (don't build yet): everything else — teams, integrations, dark mode, AI everything.\nRule of thumb: if v1 feels embarrassingly small, it's the right size. Stripe's v1 was 7 lines of code to copy-paste. Yours can be one form and one button." },
        { t: "Define 'shipped' before you start", d: "Set three finish lines now, so you can't move the goalposts later:\n• Day 14: landing page live, collecting emails.\n• Day 21: MVP works end-to-end — someone can sign up, use the core feature, and pay.\n• Day 30: launched publicly in at least 3 places.\nDone is measurable. 'Almost done' is a feeling — and it lies." },
        { t: "Beat the fear now, not later", d: "Around Day 18 you will think: \"someone already built this, better.\" Answer it today:\n• Competitors = proven demand (Day 4).\n• You only need a tiny slice: 200 customers is life-changing MRR and rounding error to competitors.\n• Your niche focus and your speed ARE the differentiation.\nWrite your answer to \"why will people pick mine?\" in one sentence. Keep it." },
        { t: "Your daily rhythm for the next 23 days", d: "From tomorrow:\n• 1 lesson here (~10 minutes).\n• 30–60 minutes of doing: prompting, testing, posting.\n• One tiny visible win a day — a page live, a button working, an email collected.\nConsistency beats intensity. A streak of small wins ships a product; a weekend of heroics ships burnout." }
      ],
      action: "Write your commitment sentence, your v1/Later lists, and your one-line answer to 'why will people pick mine?' — then tell one real person your Day 30 launch date.",
      quiz: [
        { q: "What's the right response if you can't choose between two validated ideas?", a: ["Pick the one with the most reachable audience and commit for 30 days", "Build both at the same time", "Wait for more validation data", "Let a coin flip decide, then switch daily"], c: 0, e: "A decided founder with a decent idea beats a waffling founder with a perfect one. Switching resets all momentum to zero." },
        { q: "What belongs in v1?", a: ["One core action, plus login and payments — nothing else", "Every feature competitors have", "Teams, integrations, and a mobile app", "Whatever the AI suggests adding"], c: 0, e: "v1 exists to deliver the core outcome and collect money. Everything else waits for real customer feedback. Embarrassingly small = right-sized." },
        { q: "Why define 'shipped' with dates and checkboxes before you start building?", a: ["So you can't move the goalposts when it feels 'almost done'", "Because investors require it", "It makes the AI code faster", "Deadlines are legally binding"], c: 0, e: "'Almost done' is a feeling that can last forever. Landing page by Day 14, working MVP by Day 21, public launch by Day 30 — measurable and honest." },
        { q: "Mid-build, you discover a polished competitor. What's the pre-committed answer?", a: ["Demand is proven, and I only need a tiny niche slice they ignore", "Quit and pick a new idea immediately", "Copy their app exactly", "Cut your price to free"], c: 0, e: "200 customers is rounding error to them and life-changing MRR to you. Your niche focus is the moat — this is why you answered the fear on Day 7." },
        { q: "Which daily rhythm actually ships products?", a: ["Small consistent progress: one lesson + 30–60 min of building daily", "One heroic 20-hour weekend per month", "Planning for 3 weeks, building in week 4", "Waiting for motivation to strike"], c: 0, e: "Like the streak in this app: small daily wins compound. Momentum is the only project management system a solo founder needs." }
      ]
    }
  ]
});
