window.COURSE_WEEKS = window.COURSE_WEEKS || [];
window.COURSE_WEEKS.push({
  week: 4,
  title: "Launch & Grow MRR",
  goal: "Launch publicly, get your first customers, and build the systems that grow revenue.",
  days: [
    {
      day: 22,
      title: "Copy That Converts",
      emoji: "✍️",
      intro: "Between here and your first dollar stands one thing: words. Copywriting is the highest-ROI skill in indie business — and it follows learnable formulas.",
      cards: [
        { t: "Benefits, not features", d: "A feature is what the product does; a benefit is what the customer GETS.\n• Feature: \"PDF export.\" Benefit: \"Send clients quotes that look like a big company made them.\"\n• Feature: \"Autosave.\" Benefit: \"Never lose a quote to a dead phone battery.\"\nFormula: feature + \"which means…\" = benefit. Run every line on your site through it." },
        { t: "The PAS formula", d: "The oldest, most reliable sales structure:\n• Problem — name it in their words: \"Quoting jobs at 9pm after a full day on site.\"\n• Agitate — make it vivid: \"Every slow quote is a job your faster competitor wins.\"\n• Solve — enter your product: \"QuoteFast sends professional quotes in 2 minutes, from your truck.\"\nPAS works for landing pages, launch posts, emails, and ads. When stuck, reach for it." },
        { t: "Steal your customers' words", d: "Your Day 5 interviews and Day 21 tests are a copywriting goldmine. When a landscaper says \"I lose jobs because I quote too slow\" — that IS your headline, verbatim.\nCustomer language beats clever language every time, because readers recognize themselves in it. Keep a 'voice of customer' note file; harvest it for every headline, email, and launch post you ever write." },
        { t: "Social proof, honestly bootstrapped", d: "People trust people, not claims. In order of power: specific results (\"cut my quoting time from 45 to 4 minutes\") > named testimonials > usage numbers (\"200 quotes sent\") > logos.\nNo customers yet? Use beta tester quotes (with permission), your waitlist size, or an honest builder's note: \"Built by a landscaper who got tired of 9pm quoting.\" Honest and specific beats inflated and vague — and you can never get caught telling the truth." },
        { t: "One page, one action", d: "Every page needs exactly one job. Landing page → start the trial. Pricing page → pick a plan. Every extra button, link, and idea bleeds conversion.\nThe end-of-page CTA formula: restate the outcome + kill the risk: \"Start sending 2-minute quotes — free for 14 days, no card required.\" Then stop typing. Asking twice for different things means getting neither." }
      ],
      action: "Rewrite your landing page using today's formulas: PAS structure, every feature translated to a benefit, at least one real customer/tester quote, one single CTA. Ask AI to critique it as a skeptical customer, then ship the best version.",
      quiz: [
        { q: "What's the difference between a feature and a benefit?", a: ["A feature is what it does; a benefit is what the customer gets", "They're synonyms", "Benefits are for enterprise sales only", "Features convert better"], c: 0, e: "'PDF export' vs 'quotes that look like a big company made them.' Use 'which means…' to convert every feature into the thing people actually buy." },
        { q: "What does PAS stand for?", a: ["Problem, Agitate, Solve", "Price, Advertise, Sell", "Product, Audience, Strategy", "Plan, Act, Ship"], c: 0, e: "Name the pain in their words, make it vivid, then present your product as the relief. The most durable structure in sales copywriting." },
        { q: "Where does the best copywriting language come from?", a: ["Your customers' own words from interviews and tests", "A thesaurus", "Competitor slogans", "Corporate jargon generators"], c: 0, e: "When a customer says 'I lose jobs because I quote too slow' — that's a headline. Readers convert when they recognize their own words." },
        { q: "You have zero customers. What social proof CAN you use honestly?", a: ["Beta tester quotes, waitlist numbers, and an honest founder story", "Invented testimonials", "Logos of companies that never heard of you", "None — skip the section"], c: 0, e: "'Join 40 landscapers on the waitlist' and a genuine builder's note are honest AND effective. Fabricated proof destroys trust permanently when discovered." },
        { q: "Why should each page have exactly one call to action?", a: ["Multiple competing asks bleed conversion — one job per page", "Buttons are expensive", "Search engines penalize buttons", "Users enjoy fewer choices in general"], c: 0, e: "Every extra option splits attention and lowers the odds of the action you actually need. Restate the outcome, remove the risk, ask once." }
      ]
    },
    {
      day: 23,
      title: "SEO: Free Customers Forever",
      emoji: "🔎",
      intro: "SEO is slow to start and then unstoppable: articles you write once bring customers for years. Start planting seeds NOW so they're bearing fruit in month 3.",
      cards: [
        { t: "How SEO actually works", d: "People type problems into Google. Google ranks pages that best answer them. If your page ranks for \"how to quote landscaping jobs\", you get a stream of perfectly-targeted visitors, free, forever.\nSEO = choosing the right searches (keywords), publishing genuinely good answers, and accumulating credibility (links). Slow for months 1–3, compounding after." },
        { t: "Hunt long-tail keywords", d: "Skip \"invoicing software\" (giants own it). Hunt long-tail searches — specific phrases with fewer, better visitors:\n• \"landscaping quote template\"\n• \"how much to charge for lawn mowing\"\n• \"[competitor] alternative for landscapers\"\nFind them via Google autocomplete, 'People also ask', and AI: \"List 30 long-tail searches a solo landscaper might type about quoting and pricing jobs.\"" },
        { t: "Write answers, not ads", d: "Each article: genuinely answer ONE search, completely. Include a template, real numbers, actual steps — be the best result on the internet for that one query.\nMention your product once, in context (\"QuoteFast fills this template automatically\"). AI drafts, you add real expertise and voice-of-customer detail, publish weekly. 10–20 good articles is a real moat for a niche." },
        { t: "Programmatic SEO & free tools", d: "Two indie force-multipliers:\n• Tool pages — a free calculator (\"lawn mowing price calculator\") ranks well, helps people, and funnels perfect prospects to your product. AI builds one in an afternoon.\n• Comparison pages — \"[Competitor] vs QuoteFast\" and \"...alternative\" pages catch buyers actively shopping.\nBoth convert far better than blog posts because searchers are already in buying mode." },
        { t: "The technical basics (one prompt)", d: "Tell AI: \"Optimize my site's SEO basics: unique title and meta description per page, one H1 per page, descriptive image alt text, fast loading, sitemap.xml, and submit-ready for Google Search Console.\"\nThen register at Search Console (free) to see what searches you rank for. That's 90% of technical SEO for a small site — done in an hour, then it's all about content." }
      ],
      action: "Generate 30 long-tail keywords with AI, pick 5 where you can write THE best answer, and publish your first article or free tool page this week. Run the technical-SEO prompt on your site.",
      quiz: [
        { q: "Why is SEO worth starting now despite being slow?", a: ["Content compounds — an article written once brings targeted visitors for years", "It gives instant traffic on day one", "It's the only legal marketing channel", "Google pays you to publish"], c: 0, e: "Months 1–3 are quiet; then it compounds. The best time to plant the seeds is before you desperately need the fruit." },
        { q: "Which keyword should a new indie app target?", a: ["\"landscaping quote template\" — specific, winnable, high intent", "\"software\"", "\"invoicing software\" — maximum volume", "\"best app 2026\""], c: 0, e: "Long-tail searches have fewer but far better visitors, and giants haven't locked them up. Winnable and targeted beats big and impossible." },
        { q: "What makes an article rank AND convert?", a: ["Being the genuinely best answer to one specific search, with your product mentioned in context", "Repeating the keyword 100 times", "Being longer than everyone else's", "Pure product promotion"], c: 0, e: "Answer completely — template, numbers, steps. Google rewards the best answer; readers reward the one natural product mention." },
        { q: "Why do free tool pages (like calculators) work so well for indie apps?", a: ["They rank well, genuinely help, and funnel perfect prospects into your product", "They replace the need for a product", "Google requires one per site", "They're impossible for competitors to copy"], c: 0, e: "A 'lawn mowing price calculator' attracts exactly your buyers at their moment of need — and AI builds it in an afternoon." },
        { q: "What covers ~90% of technical SEO for a small site?", a: ["Titles and meta descriptions, one H1 per page, alt text, speed, a sitemap, Search Console", "Hiring an agency for $5k/month", "Buying backlinks", "Rebuilding the site quarterly"], c: 0, e: "One AI prompt plus a free Search Console account. After that, SEO is a content game, not a technical one." }
      ]
    },
    {
      day: 24,
      title: "Launch Channels",
      emoji: "📣",
      intro: "\"Build it and they will come\" is the most expensive lie in software. Today you map exactly where your first 100 customers come from.",
      cards: [
        { t: "Launch is a season, not a day", d: "Amateur launch: one big announcement, then silence, then despair.\nPro indie launch: a rolling series of small launches over weeks — communities this week, directories next, Product Hunt after, each article and feature its own mini-launch. Each one compounds: more feedback, more links, more chances to be discovered. Plan five launches, not one." },
        { t: "Communities: your first 10 customers", d: "Your first customers come from where your niche already gathers: subreddits, Facebook groups, Discords, forums.\nThe playbook: be helpful for days BEFORE posting anything about your product. Then share as a story, not an ad: \"I'm a landscaper who got tired of 9pm quoting, so I built this. Free trial, would love brutal feedback.\" Stories and feedback-asks are welcome where ads get banned." },
        { t: "Product Hunt and directories", d: "• Product Hunt: launch there once your product is stable and you have some users to support you. Real prize: a burst of early adopters, a badge, and a permanent backlink.\n• Directories: submit everywhere relevant — alternative-to sites, startup directories, niche tool lists, \"awesome\" lists. Ask AI for a list of 20 directories for your category; an afternoon of submissions pays SEO dividends for years." },
        { t: "Build in public", d: "Sharing your journey (metrics, lessons, screenshots) on X/Twitter, LinkedIn, or Indie Hackers turns strangers into rooters:\n\"Day 24 of building QuoteFast: 43 signups, 6 paying. Here's what worked…\"\nPeople follow stories and root for underdogs. Numbers (even tiny ones!) and honest lessons outperform polished announcements. Your build-in-public thread becomes a customer source AND an accountability system." },
        { t: "Cold outreach: the B2B shortcut", d: "For B2B niches, nothing beats 10 personal messages a day to ideal customers:\n\"Hi Sam — saw your landscaping company in [group]. I built a tool that turns quoting into a 2-minute job. Want a free month for honest feedback?\"\nPersonal, specific, low-pressure, genuinely valuable. Expect ~10–20% replies at this quality level. 10/day = 300/month = your first paying customers, found by hand. Unscalable — and exactly right for now." }
      ],
      action: "Write your launch calendar: which 3 communities this week, 20 directories next week, Product Hunt date, and (if B2B) your first 10 cold messages drafted in your voice. Send the first 5 today.",
      quiz: [
        { q: "What does a professional indie launch look like?", a: ["A rolling series of small launches across weeks and channels", "One big announcement day", "Waiting for journalists to notice", "Buying a Super Bowl ad"], c: 0, e: "Communities, directories, Product Hunt, each article — five small launches compound where one big bang fizzles." },
        { q: "What's the right way to share your product in a niche community?", a: ["Be helpful first, then share it as an honest story asking for feedback", "Post 'BUY MY APP' with a link, daily", "DM every member the pricing page", "Post once in every subreddit that exists"], c: 0, e: "'I had this problem, built this, would love brutal feedback' is welcomed. Ads get banned; stories and feedback-asks start conversations that convert." },
        { q: "Besides launch-day traffic, what lasting value does Product Hunt + directories give?", a: ["Permanent backlinks and discovery surfaces that feed SEO for years", "Guaranteed #1 product of the day", "Free hosting credits", "Legal protection for your idea"], c: 0, e: "Every listing is a link and a doorway. An afternoon of directory submissions quietly compounds into search credibility." },
        { q: "Why does 'building in public' work?", a: ["People follow honest stories and root for underdogs — attention becomes customers", "It hides your idea from competitors", "Platforms pay for posts", "It replaces having a good product"], c: 0, e: "Real numbers and lessons — even tiny ones — outperform polished PR. The audience you build roots for you, buys from you, and refers." },
        { q: "What makes cold outreach work for B2B indie apps?", a: ["Personal, specific, low-pressure messages offering genuine value — 10 a day, by hand", "Blasting 10,000 templated emails", "Messaging only investors", "Waiting for inbound instead"], c: 0, e: "'Saw your company in [group] — built this for exactly your problem — free month for feedback?' Unscalable by design, and how first customers are actually won." }
      ]
    },
    {
      day: 25,
      title: "Email & Onboarding",
      emoji: "📬",
      intro: "You own your email list — no algorithm can take it away. And the emails users get in their first week decide whether they become customers or ghosts.",
      cards: [
        { t: "Email is the channel you OWN", d: "Social reach rents attention from an algorithm; email is yours forever. From day one, funnel everything toward the list: landing page signups, free tool users, blog readers.\nTools: Resend, Loops, or MailerLite for app + marketing email (all have free tiers). Your list of 300 niche subscribers will outsell 10,000 random followers — repeatedly, measurably." },
        { t: "The onboarding sequence", d: "New signups get an automatic sequence during their trial:\n• Day 0 — welcome: one sentence from you (a human!), one clear first step.\n• Day 1 — the core win: shortest path to the activation moment (Day 20).\n• Day 3 — a use case + a real result.\n• Day 7 — story + social proof.\n• Day 11–13 — trial ending: what they lose, one-click upgrade.\nFive emails, written once with AI's help, converting trials while you sleep — forever." },
        { t: "Write emails like a person", d: "Rules that double open and reply rates:\n• From a name (\"Otto from QuoteFast\"), not a brand.\n• Subject lines like a friend texts: \"your first quote?\" not \"Unlock Your Productivity Journey™\".\n• Plain text beats fancy HTML for indie tools.\n• One email, one point, one link.\n• End early ones with a real question (\"what are you trying to get done?\") — replies teach you AND train inboxes to not mark you as spam." },
        { t: "Nudge at the moment of drop-off", d: "Behavior-triggered emails beat scheduled ones:\n• Signed up, never activated (24h) → \"Stuck? Here's the 2-minute path\" + a direct link into the app.\n• Activated, then quiet a week → \"Did the quote win the job?\"\nYou defined these exact events in your analytics on Day 20 — now they trigger saves. Ask AI to wire events to emails; it's an afternoon job." },
        { t: "The launch-week newsletter habit", d: "Beyond automation, mail your whole list when something happens: a launch, a feature, a customer win, a lesson learned. Every 1–2 weeks is plenty.\nKeep the ratio: mostly useful or interesting, occasionally an ask. A list that hears from you regularly buys when you launch (Day 30), answers surveys, and refers friends. A list you only mail when selling learns to ignore you." }
      ],
      action: "Set up your email tool and write your 5-email onboarding sequence with AI's help — in YOUR voice, ending email one with a genuine question. Turn it on for all new signups.",
      quiz: [
        { q: "Why is email 'the channel you own'?", a: ["No algorithm controls whether your message reaches subscribers", "Email is newer than social media", "Emails can't be ignored", "Email marketing is free at any scale"], c: 0, e: "Social reach can vanish with an algorithm change. Your list is portable, direct, and yours — 300 niche subscribers beat 10,000 random followers." },
        { q: "What's the goal of a trial onboarding sequence?", a: ["Guide users to the activation moment, then convert the trial before it ends", "Send daily discounts", "Test if email works", "Fill inboxes with feature lists"], c: 0, e: "Welcome → core win → use case → proof → trial-ending ask. Written once, converting forever. This is a literal money machine you build in an afternoon." },
        { q: "Which email style wins for indie products?", a: ["Plain text from a real name, one point, one link, subject like a friend's text", "Heavy HTML with five banners", "ALL CAPS URGENT subject lines", "One monthly 3,000-word digest of everything"], c: 0, e: "'your first quote?' from 'Otto' gets opened and replied to. Corporate blasts get archived. Human beats polished." },
        { q: "A user signed up 24 hours ago and never activated. Best move?", a: ["A triggered email with the shortest path to first value, linking into the app", "Nothing — they'll figure it out", "Immediately delete the account", "A discount on the annual plan"], c: 0, e: "The drop-off moment is when help lands. You already track activation (Day 20) — wiring it to a nudge email recovers users who'd otherwise ghost." },
        { q: "How do you keep a list healthy between launches?", a: ["Mail useful things regularly (every 1–2 weeks) so occasional asks land", "Only email when selling something", "Email three times a day", "Never email — save it all for launch"], c: 0, e: "Lists you only mail to sell learn to ignore you. Mostly-useful, occasionally-asking lists open, click, buy, and refer." }
      ]
    },
    {
      day: 26,
      title: "Retention: Keep Them Paying",
      emoji: "🔁",
      intro: "MRR has a silent killer: churn. Acquiring a customer who leaves in month 2 is a treadmill. Retention is where recurring revenue actually gets built.",
      cards: [
        { t: "The bucket math", d: "MRR growth = new revenue − churned revenue. At 10% monthly churn, you lose ~⅔ of a year's customers — growth becomes running up a down escalator.\nGet churn to 3–5% and the same acquisition effort compounds into real MRR. Rule of thumb: past your first ~20 customers, an hour spent on retention usually beats an hour spent on acquisition." },
        { t: "Retention starts at activation", d: "Users who never reach first value (Day 20) always churn — they were never really customers. Users who hit value fast and often, stay.\nThe highest-leverage retention work happens in the first session: shorten the path to the first win. Pre-fill examples, cut optional steps, show the outcome early. 'Time to value' is measured in minutes, and every minute costs you subscribers." },
        { t: "Become a habit or a system", d: "Products retain when they're woven into a routine:\n• Habit hooks: the Monday-morning report email that pulls them back weekly.\n• Stored value: their quotes, clients, and history live in your app — leaving means losing it.\n• Workflow position: you're HOW they send quotes now, not an extra step.\nAsk of every feature: does this deepen the routine, the data, or the workflow? Those retain. Novelties don't." },
        { t: "Exit interviews & saves", d: "When someone cancels, one automatic question: \"What made you cancel today?\" The answers cluster fast: missing feature, too expensive, didn't use it, found alternative — each cluster is a different fix.\nAdd a save offer matched to the reason: didn't-use → a concierge setup call; too-expensive → pause plan or downgrade tier instead of goodbye. Saving 1 in 5 cancellations is realistic and compounds hugely." },
        { t: "Watch failed payments (dunning)", d: "A surprising chunk of churn isn't a decision — it's an expired card. This 'involuntary churn' can be 20–40% of the total.\nThe fix is boring and automatic: Stripe's Smart Retries + emails on failed payments (Stripe has built-in settings; enable them, or prompt AI to). Free MRR recovered forever, one afternoon of setup. Check it's on before you launch." }
      ],
      action: "Enable Stripe's failed-payment retries and cancellation email. Add a one-question exit survey. Then list 3 changes that would shorten a new user's time-to-first-value, and ship one.",
      quiz: [
        { q: "Why does churn matter more as you grow?", a: ["Churned revenue subtracts from every month's growth — a leaky bucket caps your MRR", "Churn only matters for enterprises", "Churn improves your metrics", "New customers always outpace cancellations"], c: 0, e: "At 10% monthly churn you're refilling a draining bucket. At 3–5%, the same marketing effort compounds into real recurring revenue." },
        { q: "Which users churn essentially 100% of the time?", a: ["Users who never reach first value (never activate)", "Users on annual plans", "Users who email support", "Users acquired from SEO"], c: 0, e: "No value experienced = no reason to stay. That's why time-to-first-value and onboarding are retention work, not just polish." },
        { q: "What makes a product hard to leave (in a good way)?", a: ["Being woven into routine — habit hooks, stored data, workflow position", "Hiding the cancel button", "Long contracts with penalties", "Weekly redesigns"], c: 0, e: "The Monday report pulls them back; their client history lives with you; you're how the job gets done. That's earned retention, not a lock-in trick." },
        { q: "What's the point of a one-question exit survey?", a: ["Cancellation reasons cluster, and each cluster has a different fix (and save offer)", "To guilt users into staying", "Legal compliance", "To slow down cancellations"], c: 0, e: "'Too expensive' wants a downgrade path; 'didn't use it' wanted onboarding help. You can't fix churn you don't understand — and saving 1 in 5 is realistic." },
        { q: "What is involuntary churn and its fix?", a: ["Failed payments (expired cards) — fixed by automatic retries and dunning emails", "Users canceling out of anger", "A Stripe processing fee", "Churn caused by competitors"], c: 0, e: "Up to a third of churn is just card failures. Stripe's Smart Retries + failure emails recover it automatically — enable before launch." }
      ]
    },
    {
      day: 27,
      title: "Support & Feedback Loops",
      emoji: "🎧",
      intro: "As a solo founder, support isn't a cost center — it's your unfair advantage, your research lab, and your best marketing, all disguised as answering emails.",
      cards: [
        { t: "Support IS the product (at your size)", d: "Big competitors route users through ticket systems and chatbots. You reply personally in an hour. For many customers, THAT is the reason to pick and stay with the indie option.\nEarly on: a simple support@ email + a reply-time habit beats any helpdesk software. Sign replies with your name. 'Talked to the founder and they fixed it same-day' is a story customers retell — that's marketing you can't buy." },
        { t: "Every ticket is research", d: "Keep a simple feedback log (spreadsheet is fine): date, user, plan, ask/complaint, theme.\nWeekly, tally the themes. Three people confused by the same button = fix the button, not the users. Five requests for one feature from PAYING users = strong roadmap signal. One loud request from a free user who'll 'definitely upgrade if...' = politely noted, weighted accordingly." },
        { t: "Fix the question, not just the user", d: "Every repeated question is a product bug wearing a costume:\n• Same how-do-I question 3× → the UI is unclear; relabel or add a hint where confusion strikes.\n• Same setup issue → improve onboarding or automate that step.\n• Write the answer once in a public FAQ/docs page; link it, and let it deflect the next ten.\nGoal: each ticket type gets answered, then engineered out of existence." },
        { t: "Say no with a roadmap", d: "You'll get more requests than you can build — and building every request bloats your product into mush. The polite no:\n\"Great idea — adding it to the roadmap to see how often it comes up. Here's what's coming next: [1–2 items].\"\nA public roadmap (a simple page or Trello board) makes 'not yet' feel like transparency instead of rejection, and its vote-counts become your prioritization." },
        { t: "Close the loop, win a fan", d: "When you ship something a user asked for, tell them personally: \"You asked for X three weeks ago — it's live. Thank you.\"\nThis single habit converts requesters into evangelists; people who feel heard renew, refer, and write the testimonials your Day 22 copy needs. It costs one email. Almost nobody does it. Be the one who does." }
      ],
      action: "Set up support@your domain, create your feedback log, and draft a public roadmap page with 3 'coming next' items. If anyone has already given feedback — close the loop with them today.",
      quiz: [
        { q: "Why is support an indie ADVANTAGE over big competitors?", a: ["Personal, fast, founder-signed replies are something giants structurally can't offer", "Indies can afford better helpdesk software", "Support doesn't matter at small scale", "Chatbots outperform humans"], c: 0, e: "'The founder replied in an hour and fixed it' keeps customers and generates retold stories. It's retention and marketing disguised as email." },
        { q: "Three users this week asked how the same button works. The right fix is…", a: ["Change the button/label — repeated questions are product bugs in costume", "Send all three the same explanation", "Add a tutorial video course", "Assume users don't read"], c: 0, e: "Answer it once, then engineer the confusion out of existence. Docs deflect; design fixes eliminate." },
        { q: "How should you weigh feature requests?", a: ["Tally themes weekly; repeated asks from PAYING users rank highest", "Build whatever was requested most recently", "Build everything requested", "Ignore all requests — vision only"], c: 0, e: "Five paying customers asking for the same thing is a roadmap. One free user's 'I'd totally upgrade if…' is a data point, politely noted." },
        { q: "What makes 'no' land well with customers?", a: ["A public roadmap: 'added to the list — here's what's coming next'", "Ignoring the request silently", "Promising everything, delivering later", "Explaining why their idea is bad"], c: 0, e: "Transparency converts rejection into participation. Roadmap votes also quietly become your best prioritization signal." },
        { q: "You just shipped a feature a customer requested weeks ago. What's the high-ROI move?", a: ["Email them personally: 'You asked — it's live. Thank you.'", "Nothing — they'll notice", "A press release", "Charge them extra for it"], c: 0, e: "Closing the loop turns requesters into evangelists. One email; renewals, referrals, and testimonials follow. Almost nobody does it." }
      ]
    },
    {
      day: 28,
      title: "Money & Legal Basics",
      emoji: "🧾",
      intro: "Thirty minutes of boring setup prevents genuinely scary problems later. Not legal advice — a map of what to ask about and when each thing actually matters.",
      cards: [
        { t: "Business structure, honestly staged", d: "• $0 revenue: in most places you can start as a sole proprietor — you ARE the business. Fine for validating.\n• Real revenue ($500+/month): consider an LLC (or your country's equivalent) — it separates business liability from your personal savings, and clean separation looks professional.\nIt's usually a ~$50–500 online filing. Ask a local accountant one paid question rather than guessing from forums; laws vary by country and state." },
        { t: "The two-account rule", d: "Open a separate bank account for the business the day money starts flowing. All revenue in, all expenses out, of that one account.\nWhy: taxes become a statement export instead of a shoebox of receipts; profit becomes visible at a glance; and if you form an LLC, mixing personal and business money can undermine its protection. One account, opened in an hour, saves days every year." },
        { t: "Taxes: the honest simple version", d: "Software revenue is taxable income — set aside ~25–30% of profit as you earn it (a savings sub-account works).\nSales tax/VAT on software varies wildly by country and even US state. This is exactly what a merchant of record (Day 17 — Lemon Squeezy, Paddle) solves: they handle global tax for their ~5% fee. At small scale, that trade is usually worth it purely in avoided anxiety and admin." },
        { t: "Terms, privacy, and the email law trio", d: "Before real users:\n• Terms of Service + Privacy Policy pages — AI drafts solid indie-standard ones; there are also free generators. Have them exist; perfection later.\n• If you have EU users, GDPR basics: say what you collect, let users export/delete their data (Supabase makes this doable; one AI prompt adds it).\n• Marketing email needs an unsubscribe link and your real info — every legit email tool (Day 25) handles this automatically." },
        { t: "Protect the boring crown jewels", d: "Five-minute insurance policies:\n• Use a password manager + two-factor auth on GitHub, Stripe, Supabase, email, and your domain registrar. (Your domain/email account is the master key to everything — guard it hardest.)\n• Turn on database backups (Supabase has it built in — verify it's on).\n• Keep your domain auto-renewing with a working payment method.\nAn afternoon of this prevents the three most common indie disasters: account takeover, data loss, and a lapsed domain." }
      ],
      action: "Do the five-minute protections now (2FA everywhere, backups on, domain auto-renew). Ask AI to draft your Terms + Privacy pages. Note when your revenue threshold for LLC + separate account will be.",
      quiz: [
        { q: "When does forming an LLC (or equivalent) typically become worth it?", a: ["Once real revenue flows — it separates business liability from personal savings", "Before writing any code", "Never, for software", "Only after $1M in revenue"], c: 0, e: "Validate first as a sole proprietor; formalize when there's something to protect. A one-question consult with a local accountant beats forum guessing." },
        { q: "What's the two-account rule?", a: ["Business money flows through its own bank account, never mixed with personal", "Have two Stripe accounts", "Two-factor auth on two devices", "Two people must approve expenses"], c: 0, e: "Clean separation makes taxes an export instead of a nightmare — and protects LLC status. Open the account the day money starts arriving." },
        { q: "What should you do with tax on profit as an indie?", a: ["Set aside ~25–30% as you earn, in a separate savings pot", "Ignore it until an audit", "Taxes don't apply to online income", "Spend it and negotiate later"], c: 0, e: "Software revenue is income. Setting aside a fixed slice as it arrives turns tax season from crisis into paperwork." },
        { q: "What's the simplest way to handle international sales tax/VAT?", a: ["Use a merchant of record (Lemon Squeezy/Paddle) — their ~5% fee covers global tax handling", "Register for VAT in 40 countries yourself", "Only sell to your own city", "Sales tax doesn't apply to software"], c: 0, e: "MoR providers legally sell on your behalf and absorb the tax complexity. At indie scale, that fee is cheap anti-anxiety insurance." },
        { q: "Which trio prevents the most common indie disasters?", a: ["2FA everywhere, database backups on, domain auto-renewing", "A lawyer, an accountant, and an agency", "Three backup laptops", "Trademarks, patents, and NDAs"], c: 0, e: "Account takeover, data loss, and a lapsed domain kill more indie apps than lawsuits ever will. An afternoon of setup closes all three doors." }
      ]
    },
    {
      day: 29,
      title: "Scaling MRR",
      emoji: "📈",
      intro: "You have a machine that turns attention into revenue. Scaling = adjusting four levers, in the smartest order — then deciding what happens after Day 30.",
      cards: [
        { t: "The four levers of MRR", d: "MRR = traffic × signup rate × paid conversion × price ÷ churn. Only four levers exist:\n1) More visitors (channels, Day 23–24).\n2) Better conversion (copy + onboarding, Day 22/25).\n3) Higher price/expansion (Day 18).\n4) Lower churn (Day 26).\nDiagnose before pushing: find your weakest number and work THAT. Doubling traffic into a broken funnel doubles nothing." },
        { t: "Raising prices: the fastest lever", d: "Underpriced (most indies are)? A price increase is instant MRR with zero code:\n• Grandfather existing customers at their price (they become your loyal base and your announcement becomes goodwill).\n• Raise for new customers only; announce plainly.\nA $19→$29 raise is +52% revenue per customer. If nobody complains about your price, it's too low. If ~20% of prospects wince, you're close to right." },
        { t: "Expansion revenue: grow without new customers", d: "Growing revenue from EXISTING happy customers is the highest-margin move:\n• Usage tiers — more quotes/clients/seats as they grow.\n• Add-ons — the premium feature heavy users beg for.\n• Annual upsell — email monthly customers at month 3: 'switch to annual, save 17%'.\nHealthy SaaS often grows 20–30% of new MRR this way. Your best prospects are the people already paying you." },
        { t: "Double down, don't diversify (yet)", d: "By now, ONE channel is probably producing most signups. The temptation is starting three new channels; the right move is usually 10× the working one.\nSEO working → publish 2× the articles. Cold outreach converting → systematize 20/day. One community delivering → become its most helpful member.\nAdd a second channel only when the first is systematized (documented, repeatable, partly automated) — or genuinely saturated." },
        { t: "After Day 30: iterate or new bet?", d: "The portfolio mindset (Day 3) needs a decision rule:\n• Signals present (activating users, some paying, feedback flowing) → iterate here; compounding beats novelty.\n• 60–90 days of honest effort, no pulse (no activation, no payments, silent users) → write down lessons, keep it running if it's cheap, start bet #2 with everything you learned.\nYou now build apps in weeks, not years. The loop is repeatable — that's the real asset you built this month." }
      ],
      action: "Compute your funnel numbers (Day 20 data): traffic → signup% → paid% → price → churn. Circle the weakest lever and write ONE specific experiment for it this week.",
      quiz: [
        { q: "Before pushing any growth lever, what should you do?", a: ["Find your weakest funnel number and work on that one", "Always buy more traffic first", "Redesign the logo", "Add three new features"], c: 0, e: "MRR = traffic × conversion × price ÷ churn. Doubling traffic into a broken funnel doubles nothing — diagnose, then push the weak lever." },
        { q: "What's the classic way to raise prices without losing existing customers?", a: ["Grandfather current customers; raise for new signups only", "Raise everyone's price overnight, silently", "Never raise prices", "Add fees hidden in the fine print"], c: 0, e: "Existing customers keep their deal (and their loyalty); new customers pay the new rate. A $19→$29 raise is +52% per customer, zero code." },
        { q: "What is expansion revenue?", a: ["More revenue from existing customers — usage tiers, add-ons, annual upgrades", "Opening an office abroad", "Raising venture capital", "Adding a second unrelated product"], c: 0, e: "Selling more to people who already trust you is the highest-margin growth there is. Healthy SaaS gets 20–30% of new MRR this way." },
        { q: "One channel drives most of your signups. What now?", a: ["Systematize and 10× that channel before adding new ones", "Abandon it for three new channels", "Keep it secret", "Reduce effort — it's already working"], c: 0, e: "Depth beats breadth for a solo founder. Double the working channel; add channel #2 only when #1 is documented, repeatable, and partly automated." },
        { q: "After 60–90 days of honest effort with zero pulse (no activation, no payments), the portfolio move is…", a: ["Record the lessons and start bet #2 with everything you learned", "Push the same approach for another year", "Conclude you can't build products", "Delete everything in frustration"], c: 0, e: "Kill criteria aren't defeat — they're the system. You can now ship in weeks; each bet is cheaper and smarter than the last." }
      ]
    },
    {
      day: 30,
      title: "Launch Day & Your Next 90",
      emoji: "🎉",
      intro: "Day 30. You went from 'I can't code' to founder with a live product. Today you launch loudly, then set the rhythm that turns this month into a business.",
      cards: [
        { t: "The launch-day checklist", d: "Morning of:\n• Payment flow tested end-to-end in LIVE mode (one real transaction, refund it).\n• Signup, core action, and upgrade tested on a phone.\n• Analytics recording; failed-payment emails on.\n• Support@ monitored; FAQ page live.\n• Launch posts drafted for each channel in each community's native tone.\nThen post everywhere on your calendar (Day 24), reply to EVERY comment fast — engagement begets reach on every platform." },
        { t: "Launch pricing with honest urgency", d: "Give people a reason to act today, not 'someday':\n\"Launch week: first 50 customers get 40% off for 12 months.\"\nHonest scarcity (real limit, real deadline) converts fence-sitters and rewards early believers — exactly the users who'll shape your product. Fake countdown timers destroy trust; real limited deals build it. When it ends, it ends." },
        { t: "Ride the wave for 72 hours", d: "Launch is a conversation, not a broadcast. For three days: answer every question, thank every sharer, DM everyone who shows real interest, fix small reported bugs same-day and SAY you did (\"fixed — refresh!\").\nVisible responsiveness multiplies every launch: watchers see a founder who ships, and each interaction bumps the post. Sleep after Thursday." },
        { t: "Your weekly operating rhythm", d: "From next week, the founder cadence:\n• Mon: metrics ritual (Day 20) — pick the week's ONE priority.\n• Tue–Thu: build/fix in slices; ship at least one visible improvement.\n• Fri: marketing — one article, one launch task, outreach batch.\n• Daily: support inbox, feedback log, close loops.\nOne focused priority a week, every week — that's how solo founders out-execute funded teams. Compounding needs consistency more than brilliance." },
        { t: "You're a builder now", d: "Look at the skill list you actually acquired: directing AI to build software, git, databases, auth, payments, deployment, copywriting, SEO, launch, retention, pricing.\nThat combination compounds for the rest of your life — every future idea is now weeks away instead of impossible. First dollar → first $100 → first $1,000 MRR: each is mostly repetition of what you did this month.\nGo launch. Then build the next thing. 🚀" }
      ],
      action: "LAUNCH. Run the checklist, post in every planned channel, and spend 72 hours responding to everything. Then write your first Monday priority for next week — and go earn dollar #1.",
      quiz: [
        { q: "What MUST be verified the morning of launch?", a: ["The live payment flow, end to end — one real transaction, then refund it", "The logo's exact shade of blue", "That competitors haven't launched", "Your follower count"], c: 0, e: "Launch traffic hitting a broken checkout is the most expensive bug you'll ever have. Test live mode, on a phone, before posting anything." },
        { q: "What makes launch urgency honest AND effective?", a: ["A real, limited deal — 'first 50 customers, 40% off for a year' — that actually ends", "A fake countdown that resets nightly", "Pretending the product is almost sold out", "No deadline at all"], c: 0, e: "True scarcity converts fence-sitters and rewards early believers. Fake urgency converts once and poisons trust forever." },
        { q: "Why respond to every comment during the 72-hour launch window?", a: ["Engagement multiplies reach, and visible responsiveness converts watchers", "Platforms fine slow responders", "To argue with critics", "It's polite but changes nothing"], c: 0, e: "Every reply bumps the algorithm and shows a founder who ships. 'Fixed — refresh!' during launch week is marketing gold." },
        { q: "What does the weekly founder rhythm look like?", a: ["Monday metrics + ONE priority, midweek shipping, Friday marketing, daily support", "Build 7 days a week, market never", "Market 7 days a week, build never", "Work only when inspired"], c: 0, e: "One focused priority per week, sustained, is how solo founders out-execute teams. The rhythm IS the strategy." },
        { q: "What's the real asset you built in these 30 days?", a: ["A repeatable loop: idea → validate → build with AI → launch → revenue", "One perfect app that must succeed", "A collection of AI prompts", "A certificate"], c: 0, e: "The app is one bet; the LOOP is the career. Every future idea is now weeks away. First dollar, then $100, then $1,000 MRR — repetition, not magic. 🚀" }
      ]
    }
  ]
});
