window.COURSE_WEEKS = window.COURSE_WEEKS || [];
window.COURSE_WEEKS.push({
  week: 3,
  title: "From Demo to Paid Product",
  goal: "Add a database, user accounts, and payments — then ship a working MVP.",
  days: [
    {
      day: 15,
      title: "Databases Without Fear",
      emoji: "🗄️",
      intro: "Your app needs to remember things: users, their data, their subscriptions. That's all a database is — organized memory. Today it stops being scary.",
      cards: [
        { t: "A database is a set of smart spreadsheets", d: "Picture Google Sheets:\n• Each TABLE is a sheet (users, quotes, subscriptions).\n• Each ROW is one item (one user, one quote).\n• Each COLUMN is a property (email, created_at, price).\nThe upgrades over a real spreadsheet: it handles millions of rows, many users at once, and rules about who can see what. But the mental model is truly just: sheets, rows, columns." },
        { t: "Supabase: your database as a service", d: "Supabase gives you a real professional database (Postgres) with a friendly dashboard where you can SEE your tables like spreadsheets, plus user login and file storage built in.\nFree tier: 50,000 monthly active users — you'll be earning long before you pay. Firebase (Google) is the equivalent alternative. Either works; this course assumes Supabase because its dashboard is beginner-friendly." },
        { t: "Design your tables in plain English", d: "Before any code, describe what to remember:\n\"My app needs to store: users (email, name, plan). Quotes (which user owns it, customer name, line items, total, status, date).\"\nGive that to AI: \"Design the database tables for this. Explain each table and why. Keep it minimal.\"\nIt returns a schema — a blueprint of tables and columns. Understanding the schema in plain English = understanding your app's memory." },
        { t: "Rules keep users' data private", d: "One concept worth knowing by name: Row Level Security (RLS). It means rules like \"users can only read and edit their OWN rows.\"\nWithout it, user A could peek at user B's data — a real and common vibe-coding disaster. Your job is one sentence in every database prompt: \"Enable row level security so users can only access their own data.\" The AI writes the rules; you insist they exist." },
        { t: "You can always look at your data", d: "The Supabase dashboard shows your tables live. When you test your app and save something, refresh the dashboard — the new row appears.\nThis is your debugging superpower: 'the app says saved, but did it save?' has a visible answer. Non-coders who look at their data catch problems that mystify people who only look at their screens." }
      ],
      action: "Create a free Supabase account and project. Then write your app's tables in plain English ('I need to store…') and ask AI to design the minimal schema with row level security.",
      quiz: [
        { q: "What's the right mental model for a database?", a: ["Smart spreadsheets: tables are sheets, rows are items, columns are properties", "A mysterious black box", "A folder of Word documents", "The same thing as the frontend"], c: 0, e: "Users table, one row per user, columns like email and plan. If you can imagine the spreadsheet, you can direct the database work." },
        { q: "What does Supabase give you?", a: ["A managed database plus login and storage, with a visual dashboard, free tier included", "A paid team of developers", "An app store for databases", "Just a code editor"], c: 0, e: "Backend-as-a-service: professional infrastructure without hiring or server management. Free until roughly 50k monthly users." },
        { q: "What's the right FIRST step in designing your database?", a: ["Describe in plain English what your app must remember, and let AI design the schema", "Write SQL by hand", "Copy a random schema from the internet", "Skip the database and hope"], c: 0, e: "'Store users (email, plan) and quotes (owner, items, total, status)' is a complete professional-grade instruction. The schema is just its translation." },
        { q: "What does Row Level Security (RLS) prevent?", a: ["User A reading or editing user B's data", "Slow page loads", "Spam emails", "High hosting bills"], c: 0, e: "It's the rule 'users only touch their own rows.' Always include 'enable row level security' in database prompts — it's the #1 security mistake in AI-built apps." },
        { q: "Your app says 'Saved!' but you're not sure it worked. How do you check?", a: ["Open the Supabase dashboard and look for the new row in the table", "Assume it worked", "Reinstall the app", "Ask users to double-check"], c: 0, e: "The dashboard shows your data live. Looking directly at the database is the difference between guessing and knowing." }
      ]
    },
    {
      day: 16,
      title: "User Accounts & Login",
      emoji: "🔐",
      intro: "Subscriptions need accounts — you must know WHO is paying and WHAT they get. Today: how login works and the one rule that keeps it safe.",
      cards: [
        { t: "Why your app needs accounts", d: "Accounts connect three things: a person, their data, and their subscription.\nWhen someone logs in, your app knows: show THEIR quotes (not someone else's), check THEIR plan (free or pro), and gate features accordingly. No accounts = no way to charge monthly. It's the skeleton of every subscription product." },
        { t: "Never build your own login", d: "The #1 rule of app security: don't invent authentication. Storing passwords safely, reset flows, session handling — professionals get this wrong constantly.\nInstead use ready-made auth: Supabase Auth, Firebase Auth, or Clerk. They've solved it, they maintain it, they're free at your scale. Your prompt: \"Add Supabase authentication to my app.\" Done." },
        { t: "Pick easy login options", d: "Every login method adds friction or removes it:\n• Magic links — user enters email, clicks a link, they're in. No password to forget. Great default for B2B tools.\n• Google sign-in — one tap for anyone with Gmail. Excellent second option.\n• Email + password — familiar but adds 'forgot password' support burden.\nStart with magic links + Google. You can add more later." },
        { t: "What a 'session' is", d: "After login, the app gives the browser a token — a temporary ID badge. Every request says \"it's me, badge #123\" so users don't re-login every click.\nWhy you care: when a tester says \"it keeps logging me out\" or \"I'm logged in but it says I'm not\", you can say to the AI: \"Sessions seem broken — investigate token expiry.\" Vocabulary = debugging power." },
        { t: "Gate features by plan", d: "Once accounts exist, your app checks the user's plan before showing paid features:\n\"Free users can create 3 quotes total. Pro users ($19/month) get unlimited quotes plus PDF export.\"\nThat sentence IS your business model, and it's a complete AI instruction. Tomorrow Stripe flips users from free to pro automatically when they pay — closing the loop." }
      ],
      action: "Tell your AI: 'Add Supabase auth with magic links and Google sign-in. After login, show the user's email on screen so I can verify it works.' Test with your real email.",
      quiz: [
        { q: "Why do subscription apps need user accounts?", a: ["To connect a person to their data and their subscription", "To collect data to sell", "Because app stores require it", "To send more newsletters"], c: 0, e: "Who is this? What's theirs? What did they pay for? Accounts answer all three — no accounts, no MRR." },
        { q: "What's the #1 rule about login systems?", a: ["Never build your own — use Supabase Auth, Firebase Auth, or Clerk", "Always build your own for control", "Store passwords in a spreadsheet", "Make users log in every click"], c: 0, e: "Password security is a minefield professionals still step on. Ready-made auth is safer, faster, and free at your scale." },
        { q: "What is a magic link?", a: ["A login link emailed to the user — no password to create or forget", "A paid Supabase add-on", "A phishing technique", "A type of database row"], c: 0, e: "Email → click → logged in. Fewer forgotten passwords means less friction for users and fewer support requests for you." },
        { q: "A tester says 'it keeps logging me out.' What's the useful vocabulary?", a: ["'Sessions seem broken — investigate token expiry'", "'The internet is down'", "'The database is full'", "'CSS is leaking'"], c: 0, e: "Sessions are the ID badge that keeps users logged in. Naming the concept points the AI straight at the right area." },
        { q: "What does 'free users get 3 quotes, pro gets unlimited' represent?", a: ["Your business model, expressed as a feature gate AI can build", "An error message", "A marketing slogan only", "A database backup policy"], c: 0, e: "Plan-gating is where product meets revenue. It's one clear sentence — and it's buildable exactly as written." }
      ]
    },
    {
      day: 17,
      title: "Taking Money: Stripe",
      emoji: "💳",
      intro: "The moment of truth for any business: can you accept a payment? Today you wire up the machinery of MRR.",
      cards: [
        { t: "How Stripe works", d: "Stripe handles cards, subscriptions, invoices, and fraud for ~2.9% + 30¢ per transaction. No monthly fee — they earn when you earn.\nYour app never touches card numbers: you send users to a Stripe-hosted checkout page, they pay there, Stripe tells your app 'this user paid.' That separation keeps you out of scary compliance territory entirely." },
        { t: "The subscription flow, end to end", d: "1) User clicks Upgrade in your app.\n2) They land on Stripe Checkout (hosted by Stripe) and enter their card.\n3) Stripe notifies your app: 'this customer is now subscribed' — via a webhook (a message sent to your backend).\n4) Your app updates the user's row: plan = 'pro'.\n5) Stripe re-charges monthly and reports failures/cancellations the same way.\nAI wires this in an afternoon. You just learned the vocabulary to direct it." },
        { t: "Webhooks: worth knowing by name", d: "A webhook = one service automatically calling your app when something happens. \"When a payment succeeds, Stripe POSTs to my app, which flips the user to pro.\"\nWhy care: webhook bugs are THE classic payments bug — user pays, app doesn't upgrade them. If a tester reports paying without unlocking, tell AI: \"Check the Stripe webhook handling.\" You'll look like a pro, because you'll be acting like one." },
        { t: "Test mode: play money first", d: "Stripe has a test mode with fake cards (4242 4242 4242 4242 is the famous one). Build and test the entire flow — subscribe, upgrade, cancel — without a real dollar moving.\nOnly after everything works do you flip to live mode and connect your bank account. Never test with real cards; never launch without testing the cancel flow too." },
        { t: "Or let a merchant of record handle taxes", d: "Selling software internationally can involve VAT/sales tax in many countries. Alternatives like Lemon Squeezy, Paddle, or Polar act as the 'merchant of record' — they charge slightly more (~5%) but handle ALL sales tax for you.\nHonest guidance: at $0 MRR this is not your bottleneck. Start with Stripe (or Lemon Squeezy if taxes worry you), note the issue, revisit when revenue is real." }
      ],
      action: "Create a Stripe account and stay in test mode. Ask AI: 'Add a $19/month subscription with Stripe Checkout. When payment succeeds via webhook, set the user's plan to pro.' Then subscribe yourself with card 4242 4242 4242 4242.",
      quiz: [
        { q: "How does Stripe charge you?", a: ["~2.9% + 30¢ per transaction — no monthly fee", "$500/month flat", "It's free forever", "They take 30% like app stores"], c: 0, e: "Stripe earns only when you do. On a $19 subscription, you keep about $18.15 — compare to $13.30 after an app store's 30%." },
        { q: "Why does your app never touch card numbers?", a: ["Users pay on a Stripe-hosted checkout page, keeping you out of card-security compliance", "Cards are typed into your database", "Payments happen by wire transfer", "The browser blocks card numbers"], c: 0, e: "Stripe Checkout handles the sensitive parts on their servers. You get the 'they paid' signal without the compliance nightmare." },
        { q: "What is a webhook?", a: ["An automatic message from one service to your app when something happens", "A fishing technique", "A type of password", "A CSS animation"], c: 0, e: "'Payment succeeded → Stripe calls your app → app flips user to pro.' When someone pays but doesn't get upgraded, webhook handling is the first suspect." },
        { q: "What is Stripe test mode for?", a: ["Testing the whole payment flow with fake cards before real money moves", "Testing your app's speed", "A cheaper tier of Stripe", "Practicing customer support"], c: 0, e: "Card 4242 4242 4242 4242 lets you rehearse subscribe/cancel/fail flows safely. Flip to live mode only after the full loop works." },
        { q: "What does a 'merchant of record' like Lemon Squeezy or Paddle do for ~5%?", a: ["Handles international sales tax/VAT for you", "Writes your app's code", "Guarantees you customers", "Provides free hosting"], c: 0, e: "They legally sell on your behalf and deal with global tax. A real consideration eventually — but not a reason to delay your first dollar." }
      ]
    },
    {
      day: 18,
      title: "Pricing Your App",
      emoji: "🏷️",
      intro: "Pricing feels like guessing. It isn't — there are rules of thumb that fit indie apps remarkably well. Biggest one: you're probably about to underprice.",
      cards: [
        { t: "Price the outcome, not your effort", d: "Customers don't care that AI built your app in 3 weeks. They care what it's worth to THEM.\nA tool that saves a business 2 hours/week saves ~$100+/month of time — $29/month is obviously fair. A consumer habit app competes with $3 impulse purchases. Same effort to build; wildly different ceilings. This is why Day 4 pushed you toward B2B." },
        { t: "The indie pricing bands", d: "Where indie products tend to land:\n• Consumer apps: $3–10/month — high churn, needs volume.\n• Prosumer tools (creators, freelancers): $9–29/month.\n• Small business B2B: $19–99/month — the indie sweet spot.\n• Anything saving real business money: $49+/month.\nStarting rule: pick the band for your audience, then choose the HIGHER of the two numbers you're debating. You can discount; un-raising is harder." },
        { t: "Three tiers, one obvious choice", d: "Classic structure:\n• Free or trial — tastes the value, hits a wall (3 quotes total).\n• Pro (your real product) — the plan you WANT everyone on. Price it right; make it obviously best.\n• Premium at 2–3× — extras for power users. Some will take it; it also makes Pro look cheap.\nAnchor high: listing Premium first makes Pro feel like the sensible middle. Most revenue will be Pro — by design." },
        { t: "Free trial vs freemium", d: "• Free TRIAL (14 days, then pay): creates urgency; converts 10–25% of trials. Best default for B2B tools.\n• FREEMIUM (free forever, limited): grows slowly, most users never pay (2–5% convert), but fuels word of mouth.\nIndie default: 14-day trial, no credit card required, with a clear in-app countdown. Simple, honest, effective. Freemium only if virality is core to your growth plan." },
        { t: "Annual plans: instant cash flow", d: "Offer yearly at ~2 months free (pay for 10, get 12). Benefits:\n• Cash up front funds your marketing.\n• Annual customers churn far less — they've committed.\n• 'Save 17%' is a genuinely honest discount pitch.\nA 'launch deal' (first 50 customers get 40% off for a year, honestly limited) creates urgency AND recruits invested early users who give feedback. That's Day 30 ammunition." }
      ],
      action: "Write your pricing: tier names, monthly and annual prices, and what's gated. Then ask an AI to critique it as a skeptical customer in your niche — and raise whatever felt too cheap.",
      quiz: [
        { q: "What should your price be based on?", a: ["The value of the outcome for the customer", "How long the app took to build", "The cheapest competitor minus a dollar", "Your monthly hosting costs"], c: 0, e: "Effort is invisible to customers; outcomes aren't. A tool saving a business hours weekly is cheap at $29/month regardless of how fast AI built it." },
        { q: "You're debating $19 vs $29 for a small-business tool. The rule of thumb says…", a: ["Pick $29 — indies underprice, and discounting later is easier than raising", "Pick $19 to be safe", "Pick $5 to beat everyone", "Make it free until you're famous"], c: 0, e: "Underpricing is the classic indie mistake. Higher prices also filter for serious customers who churn less and complain less." },
        { q: "In a 3-tier structure, what's the Premium tier's secret second job?", a: ["Anchoring — it makes the Pro tier look sensibly priced", "Generating most of the revenue", "Satisfying app store rules", "Replacing the free trial"], c: 0, e: "Some power users take Premium, but its quiet job is making Pro the obvious 'smart middle choice' — where you want most customers." },
        { q: "What's the recommended default for a B2B indie tool?", a: ["14-day free trial, no credit card required, clear countdown", "Free forever for everyone", "Payment required before seeing the app", "A 6-month trial"], c: 0, e: "Trials create urgency and convert 10–25%. Freemium converts 2–5% and suits products that grow through sharing." },
        { q: "Why offer an annual plan at ~2 months free?", a: ["Upfront cash plus dramatically lower churn from committed customers", "It looks longer on the pricing page", "Stripe requires annual plans", "Annual customers use the app less"], c: 0, e: "A year of commitment paid today funds growth and can't churn next month. 'Save 17%' is honest and effective." }
      ]
    },
    {
      day: 19,
      title: "Build Day: The MVP Core",
      emoji: "⚙️",
      intro: "Everything converges: today (and tomorrow) you build the core feature — the one thing your app does that people will pay for.",
      cards: [
        { t: "Write the golden path first", d: "Before prompting, write the golden path — the single journey that delivers the value:\n\"1) User logs in. 2) Taps 'New quote'. 3) Fills 4 fields. 4) Sees a professional quote. 5) Taps Send — customer gets it by email. 6) Quote appears in their list.\"\nSix sentences = your complete build spec. Everything not on this path is a Day 30+ problem." },
        { t: "Build in testable slices", d: "Turn the path into slices, each verifiable in minutes:\n• Slice 1: the form (fake save) — can I fill and submit it?\n• Slice 2: real save to Supabase — does the row appear in the dashboard?\n• Slice 3: the output (the formatted quote) — does it look right?\n• Slice 4: the send/export action.\n• Slice 5: the list of past items.\nOne prompt per slice. Test each. Commit each (Day 10!). This rhythm is unstoppable." },
        { t: "Use real data while testing", d: "Test with a REAL example from your niche — an actual job quote, a real client name, real prices. Fake data ('test test 123') hides problems: fields too short, totals wrong, awkward layouts with long names.\nBonus: testing with real data forces you to experience your app as a customer. Every annoyance you feel, they'll feel. Fix those first." },
        { t: "When scope creep whispers", d: "Mid-build you WILL think: \"it also needs templates… and a logo upload… and reminders…\". Write each idea in your Later list (Day 7) and keep moving.\nThe test for adding anything to v1: \"Will a customer refuse to PAY without this?\" Almost everything fails that test. Templates don't block the first dollar; a working golden path is the first dollar." },
        { t: "Definition of done for today", d: "By tomorrow night:\n• The golden path works with real data, end to end.\n• Data survives refresh and re-login (it's really in the database).\n• It works on a phone.\n• The work is committed and deployed.\nRough edges are FINE. Ugly is FINE. A working ugly product beats a beautiful plan every single day of the week." }
      ],
      action: "Write your golden path (max 6 steps) and slice list. Build slices 1–2 today: the core form/action, saving real data to Supabase. Verify rows appear in the dashboard.",
      quiz: [
        { q: "What is the 'golden path'?", a: ["The single user journey that delivers your app's core value, written as simple steps", "The most expensive pricing tier", "A git branching strategy", "The app's color scheme"], c: 0, e: "Login → do the thing → get the outcome. Writing it in ~6 sentences gives you a complete, buildable spec — and a fence against scope creep." },
        { q: "Why build in small testable slices?", a: ["Each slice is verifiable in minutes, so problems surface immediately and progress is real", "It makes the code longer", "AI can't handle big prompts at all", "Slices are required by Supabase"], c: 0, e: "Form → save → output → send → list. One prompt per slice, test, commit, next. The rhythm from Day 8, now building your actual product." },
        { q: "Why test with real data instead of 'test test 123'?", a: ["Real data exposes real problems and forces you to feel what customers will feel", "Fake data crashes databases", "Real data is faster to type", "It's a legal requirement"], c: 0, e: "Long names break layouts; real prices reveal math bugs; real use reveals annoyances. Fake data hides all of it until a customer finds it." },
        { q: "Mid-build, you're sure the app also needs templates. The v1 test is…", a: ["\"Will a customer refuse to pay without this?\" — if not, it goes on the Later list", "\"Is it cool?\"", "\"Do competitors have it?\"", "\"Can AI build it quickly?\""], c: 0, e: "Almost nothing passes the refuse-to-pay test. The golden path earns the first dollar; everything else is post-revenue polish." },
        { q: "Which MVP state is 'done' for this checkpoint?", a: ["Golden path works end-to-end with real data, on a phone, committed and deployed — even if ugly", "Pixel-perfect design with 20 features", "Works on your laptop only, undeployed", "A detailed plan for building next month"], c: 0, e: "Working-ugly-shipped beats beautiful-planned. Customers pay for outcomes, not gradients." }
      ]
    },
    {
      day: 20,
      title: "Analytics: Know What Users Do",
      emoji: "📊",
      intro: "Once strangers use your app, gut feelings stop working. A few numbers — set up in an hour — will tell you what to fix, what to build, and what to ignore.",
      cards: [
        { t: "Analytics answers three questions", d: "1) Are people coming? (visitors, and from where)\n2) Are they getting it? (signups, and % who complete the core action)\n3) Are they staying? (do they come back next week?)\nThat's it. Ignore vanity dashboards with 50 charts. Three questions, three numbers, checked weekly." },
        { t: "Privacy-friendly tools in one click", d: "• Site traffic: Plausible or Simple Analytics (~$9/month) — or free, cookie-banner-free options like Vercel Analytics to start. One script tag; AI adds it in one prompt.\n• In-app events: PostHog (generous free tier) tracks actions like 'created quote'.\nAvoid enterprise complexity. Prompt: \"Add Plausible to the landing page and PostHog events for signup, first quote created, and upgrade click.\"" },
        { t: "Track the moment of value", d: "Define your activation event — the moment a user first GETS the value: 'sent their first quote'. Not 'visited', not 'signed up' — the value moment.\nActivation rate (% of signups who reach it) is your app's most honest health metric. If 100 people sign up and 15 send a quote, your product has an onboarding problem, not a marketing problem. You'd never know without tracking it." },
        { t: "The funnel shows where people fall", d: "A funnel is the drop-off count at each step:\n100 visitors → 20 signups → 12 created a quote → 8 sent it → 2 upgraded.\nEach arrow is a leak to investigate, in order of size. Biggest leak first: why did 8 of 20 signups never create a quote? Watch one person try (Day 21) and you'll usually see exactly why." },
        { t: "A weekly dashboard ritual", d: "Every Monday, 10 minutes, write down: visitors, signups, activation rate, paying customers, MRR. In a plain spreadsheet.\nTrends matter more than any single number. Flat for 3 weeks = your current approach has stalled; change something (channel, copy, onboarding). Growing 10%/week = pour more into what's working. Numbers replace anxiety with decisions." }
      ],
      action: "Add analytics: one prompt for page analytics, one for in-app events (signup, activation action, upgrade click). Then define YOUR activation event in one sentence.",
      quiz: [
        { q: "What three questions should your analytics answer?", a: ["Are people coming? Are they getting value? Are they staying?", "What's trending on social media?", "How many lines of code exist?", "Which country has the best design taste?"], c: 0, e: "Traffic, activation, retention. Three numbers checked weekly beat fifty charts checked never." },
        { q: "What is an 'activation event'?", a: ["The moment a user first experiences the core value — like sending their first quote", "The user's first visit", "Creating an account", "Opening the pricing page"], c: 0, e: "Signup is intent; activation is value received. Users who activate stick around and pay; users who don't, silently vanish." },
        { q: "100 signups, 15 activated. What does this tell you?", a: ["You have an onboarding problem — fix the path to first value, not marketing", "You need more visitors", "Time to raise prices", "The database is too small"], c: 0, e: "More marketing pours water into a leaky bucket. An 85% activation leak is the highest-leverage fix in your whole business right now." },
        { q: "What is a funnel?", a: ["The count of users surviving each step: visit → signup → activate → pay", "A viral marketing trick", "A type of database", "A Stripe fee"], c: 0, e: "Each arrow between steps is a measurable leak. Fix the biggest leak first — that's data-driven product work in one sentence." },
        { q: "What's the recommended weekly ritual?", a: ["10 minutes every Monday: record visitors, signups, activation, customers, MRR — and act on trends", "Check analytics hourly", "Review numbers once a year", "Only look when things feel wrong"], c: 0, e: "Trends over snapshots. Flat = change something. Growing = double down. The ritual turns feelings into decisions." }
      ]
    },
    {
      day: 21,
      title: "Checkpoint: Watch a Stranger Use It",
      emoji: "🧪",
      intro: "Your MVP works — for YOU. Today it faces its first real users, and you face the most useful, humbling hour in product development.",
      cards: [
        { t: "The 5-user test", d: "Research famously shows ~5 testers uncover most usability problems. Recruit from your email list (Day 14) or niche communities: \"10 minutes on a video call, you try my tool, I shut up and watch.\"\nWatching live beats sending links: you see the hesitations, the wrong turns, the 'hmm' moments people never write down in feedback forms." },
        { t: "The golden rule: don't help", d: "Give one task — \"create and send a quote\" — then be silent. When they stall, say \"what are you thinking?\" — never \"click the blue button.\"\nEvery time you rescue them, you erase the exact data you came for. In real life you won't be there to help. The pain of watching someone struggle IS the discovery of what to fix." },
        { t: "Watch for these four signals", d: "• Hesitation — cursor circling = unclear next step.\n• Wrong turns — they click the wrong thing = your labels lie.\n• Silent abandonment — 'the moment' where they'd normally quit.\n• The face — confusion is visible before it's spoken.\nWrite timestamps and moments. Five tests produce a brutally clear, short fix list. Expect the same 2–3 issues repeatedly — that repetition is the priority order." },
        { t: "Then ask the money question", d: "After the task, ask:\n• \"Would you use this for real work this month?\"\n• \"What would make it a no-brainer?\"\n• Then: \"It'll be $19/month — would you pay that?\" and SILENCE. Let them answer.\n'Yes, and can I start now?' = gold. 'Maybe' = a polite no; ask what's missing. Squirming at price = wrong price or wrong audience. All three answers are wins: they're the truth." },
        { t: "Fix, then invite them back", d: "Spend Day 21–22 fixing only what multiple testers hit. Then email each tester: \"You said X was confusing — it's fixed. Fancy another look?\"\nThis does three things: validates the fixes, turns testers into invested early users (people root for products they shaped), and hands you your first testimonial candidates for launch week. Beta testers who feel heard become customers who tell friends." }
      ],
      action: "Recruit 3–5 testers from your email list or communities and run watch-them-use-it sessions this week. Write down every stumble. Ask the $19 question and record the exact answers.",
      quiz: [
        { q: "Why do ~5 testers suffice for a usability round?", a: ["A handful of users uncovers most problems — the same issues repeat quickly", "Five is a legal maximum", "More testers cost too much", "One tester is actually enough"], c: 0, e: "Classic usability research: the big problems surface fast and repeat. Five sessions give you a clear, prioritized fix list." },
        { q: "A tester is stuck. What do you say?", a: ["\"What are you thinking right now?\"", "\"Click the blue button on the left\"", "\"Let me just do it for you\"", "\"That part's obvious, keep trying\""], c: 0, e: "Rescuing them destroys the data. Their struggle marks exactly what to fix — in production, you won't be sitting next to them." },
        { q: "Which of these is a critical usability signal?", a: ["Hesitation and wrong clicks — they reveal unclear steps and lying labels", "Testers blinking", "Fast task completion", "Compliments about colors"], c: 0, e: "Circling cursors, wrong turns, silent quitting moments, confused faces. Timestamps of those ARE your fix list." },
        { q: "You ask 'Would you pay $19/month?' and they say 'Maybe, probably'. Translation?", a: ["That's a polite no — ask what's missing to make it a yes", "That's a guaranteed yes", "They want to invest in the company", "The price is too low"], c: 0, e: "Enthusiasm sounds like 'yes — can I start today?'. 'Maybe' is your cue to dig: wrong features, wrong price, or wrong audience." },
        { q: "After fixing what testers hit, why invite them back?", a: ["It validates fixes, creates invested early users, and seeds launch testimonials", "To bill them for testing", "To show off unrelated new features", "There's no reason to return"], c: 0, e: "'You said X was confusing — it's fixed' makes people feel heard. People who shape a product root for it, pay for it, and quote nicely about it." }
      ]
    }
  ]
});
